config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :third_blogs
  resources :second_blogs
  resources :blogs
  resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/second_blog.rb
class SecondBlog < ApplicationRecord
end

app/controllers/second_blogs_controller.rb
class SecondBlogsController < ApplicationController
  before_action :set_second_blog, only: [:show, :edit, :update, :destroy]

  # GET /second_blogs
  # GET /second_blogs.json
  def index
    @second_blogs = SecondBlog.all
  end

  # GET /second_blogs/1
  # GET /second_blogs/1.json
  def show
  end

  # GET /second_blogs/new
  def new
    @second_blog = SecondBlog.new
  end

  # GET /second_blogs/1/edit
  def edit
  end

  # POST /second_blogs
  # POST /second_blogs.json
  def create
    @second_blog = SecondBlog.new(second_blog_params)

    respond_to do |format|
      if @second_blog.save
        format.html { redirect_to @second_blog, notice: 'Second blog was successfully created.' }
        format.json { render :show, status: :created, location: @second_blog }
      else
        format.html { render :new }
        format.json { render json: @second_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /second_blogs/1
  # PATCH/PUT /second_blogs/1.json
  def update
    respond_to do |format|
      if @second_blog.update(second_blog_params)
        format.html { redirect_to @second_blog, notice: 'Second blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @second_blog }
      else
        format.html { render :edit }
        format.json { render json: @second_blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /second_blogs/1
  # DELETE /second_blogs/1.json
  def destroy
    @second_blog.destroy
    respond_to do |format|
      format.html { redirect_to second_blogs_url, notice: 'Second blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_second_blog
      @second_blog = SecondBlog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def second_blog_params
      params.require(:second_blog).permit(:title)
    end
end

app/helpers/second_blogs_helper.rb
module SecondBlogsHelper
end

app/views/second_blogs/_form.html.erb
<%= form_with(model: second_blog, local: true) do |form| %>
  <% if second_blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(second_blog.errors.count, "error") %> prohibited this second_blog from being saved:</h2>

      <ul>
      <% second_blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :second_blog_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/second_blogs/edit.html.erb
<h1>Editing Second Blog</h1>

<%= render 'form', second_blog: @second_blog %>

<%= link_to 'Show', @second_blog %> |
<%= link_to 'Back', second_blogs_path %>

app/views/second_blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Second Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @second_blogs.each do |second_blog| %>
      <tr>
        <td><%= second_blog.title %></td>
        <td><%= link_to 'Show', second_blog %></td>
        <td><%= link_to 'Edit', edit_second_blog_path(second_blog) %></td>
        <td><%= link_to 'Destroy', second_blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Second Blog', new_second_blog_path %>

app/views/second_blogs/new.html.erb
<h1>New Second Blog</h1>

<%= render 'form', second_blog: @second_blog %>

<%= link_to 'Back', second_blogs_path %>

app/views/second_blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @second_blog.title %>
</p>

<%= link_to 'Edit', edit_second_blog_path(@second_blog) %> |
<%= link_to 'Back', second_blogs_path %>